<b>Welcome to the WordPress plugin for iCharts</b>
<p>To proceed you will need an iChart URL. iChart URLs can be found though your <a href="http://icharts.net">iCharts.net</a> account.</p>
<p>If you have not already done so, please setup up an account at <a
	href="http://icharts.net">iCharts.net</a></p>
<b>Inserting an iChart method 1</b>
<p>Enter an iChart URL into a post and highlight it, click <span class='v35v_icharts'>&nbsp;</span> in the editor menu.</p>
<b>Inserting an iChart method 2</b>
<p>Click the <span class='v35v_icharts'>&nbsp;</span> in the editor menu.</p>
<p>Enter an iChart URL.</p>
<p>Click <b>Insert Chart</b></p>
<b>Inserting an iChart method 3</b>
<p>Enter <code>[ichart url="{iChart URL}"]</code> into your post.</p>
<p>Where {iChart URL} is replaced with an iChart URL.</p>
