<p style="margin:10px 0 30px 0; font-weight:bold; font-size:15px;">Welcome to the WordPress plugin for iCharts</p>

<p>You can easily add any iCharts to your WordPress posts using this simple plugin. All you need is the chart's Public URL, which can be found inside the sharing options of that chart.</p>
<p>When viewing the chart within a webpage, click on the 'Share' option in the top left navigation. In the pop-up, copy the provided direct URL and choose one of the following quick methods:</p>

<p style="margin:30px 0 0 0;"><strong>Method 1:</strong></p>
<p style="margin:10px 0 0 0;">Enter the iChart URL into a post and highlight it, click &nbsp;<span class='v35v_icharts'>&nbsp;</span> in the editor menu.</p>

<p style="margin:30px 0 0 0;"><strong>Method 2:</strong></p>
<p style="margin:10px 0 0 0;">Click &nbsp;<span class='v35v_icharts'>&nbsp;</span> in the editor menu.</p>
<p>Enter the copied iChart URL</p>
<p>Click Insert Chart</p>

<p style="margin:30px 0 0 0;"><strong>Method 3:</strong></p>
<p style="margin:10px 0 0 0;">Enter <code>[ichart url="{iChart URL}"]</code> into your post.</p>
<p>Where {iChart URL} is replaced with an iChart URL.</p>

<p style="margin:30px 0 0 0; font-weight:bold;">For more information, please refer to our <a href="http://www.icharts.net/faq/how-add-chart-wordpress-blog" target="_blank">FAQ</a></p>
<p style="margin:10px 0 10px 0; font-weight:bold;">To create your own interactive charts using iCharts please set up an account at <a href="http://icharts.net" target="_blank">iCharts.net</a></p>
