<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>iCharts</title>
<script language="javascript" type="text/javascript"
	src="<?php
	echo site_url ();
	?>/wp-includes/js/tinymce/tiny_mce_popup.js"></script>
<script language="javascript" type="text/javascript"
	src="<?php
	echo site_url ();
	?>/wp-includes/js/tinymce/utils/mctabs.js"></script>
<script language="javascript" type="text/javascript"
	src="<?php
	echo site_url ();
	?>/wp-includes/js/tinymce/utils/form_utils.js"></script>
<script language="javascript" type="text/javascript"
	src="<?php
	echo site_url ();
	?>/wp-includes/js/jquery/jquery.js"></script>
<script language="javascript" type="text/javascript"
	src="<?php
	echo $this->application ()->pluginuri () . '/application/public/js/tinymce.js?ver='.$this->application()->version();
	?>"></script>
<link rel="stylesheet" type="text/css"
	href="<?php
	echo $this->application ()->pluginuri () . '/library/public/css/style.css?ver='.$this->application()->version();
	?>
	media=" all" />
<link rel="stylesheet" type="text/css"
	href="<?php
	echo $this->application ()->pluginuri () . '/application/public/css/style.css?ver='.$this->application()->version();
	?>
	media=" all" />
<base target="_self" />
</head>
<body>
<form id='v35v_form' action='' method='post'
	class='	admin-menu v35v_settings' style='margin-bottom:0px;'>
<table class="icharts_default">
	<col/>
	<col/>
	<tfoot>
		<tr>
			<td colspan=2 style="height:30px;"><center><input type='submit' id='insert' value='Insert Chart' /></center>
		</tr>
	</tfoot>
	<tbody>
		<tr>
			<td>Chart URL</td>
			<td><input type=text style="width:230px; height:25px;" name='url' value='' /><br/>
		</tr>
	</table>
</form>
<p style="text-align:center;margin:10px 0 0 0;">For more information, please refer to our <a href="http://www.icharts.net/faq/how-add-chart-wordpress-blog" target="_blank">FAQ</a></p>

</body>
</html>